### ISSUE TITLE
👈 Do not lose focus when saving

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/remembered#5]
Currently, there is an issue that makes the app lose focus on the current note when it's saved using the "Save" button below. It may be caused by a function or a code mistake and should be fixed to leave the design working as intended.

**Comment by Diem0n** [comment]
Hi, I would like to work on this issue can you assign it to me?

**Comment by LyubomirT** [comment]
Sure thing! Thanks for your interest in contributing to this project!
